# Generated by Django 6.0.6 on 2026-06-17 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_updated_at_alter_user_first_name_and_more'),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeadminprofile',
            name='college',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='collegeadminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
