# Generated by Django 6.0 on 2026-07-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(db_index=True, max_length=6),
        ),
        migrations.AddIndex(
            model_name='passwordresetotp',
            index=models.Index(fields=['user', 'is_used'], name='accounts_pa_user_id_db304d_idx'),
        ),
    ]
