# Generated by Django 6.0 on 2026-07-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresetotp_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
