# Generated by Django 6.0 on 2026-07-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_date_of_birth_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=1),
            preserve_default=False,
        ),
    ]
