# Generated by Django 6.0 on 2026-07-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
    ]
