# Generated by Django 6.0 on 2026-07-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
