# Generated by Django 6.0 on 2026-07-22 08:59

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('text', models.TextField()),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Complaint Attachment')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('FACULTY', 'Faculty'), ('FACILITIES', 'Facilities'), ('DISCIPLINE', 'Discipline'), ('EXAMINATION', 'Examination'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('scope', models.CharField(choices=[('COLLEGE', 'College'), ('DEPARTMENT', 'Department')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SEEN', 'Seen'), ('RESOLVED', 'Resolved')], db_index=True, default='SUBMITTED', max_length=20)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='colleges.college')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='departments.department')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Status History',
                'verbose_name_plural': 'Complaint Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['category'], name='complaints__categor_8115a1_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['scope'], name='complaints__scope_bc5cab_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['college'], name='complaints__college_3efc10_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['department'], name='complaints__departm_8b32d1_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['created_at'], name='complaints__created_805464_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'COLLEGE'), ('department__isnull', True)), models.Q(('scope', 'DEPARTMENT'), ('department__isnull', False)), _connector='OR'), name='valid_complaint_scope_department'),
        ),
        migrations.AddIndex(
            model_name='complaintstatushistory',
            index=models.Index(fields=['complaint'], name='complaints__complai_611b37_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintstatushistory',
            index=models.Index(fields=['changed_at'], name='complaints__changed_99518a_idx'),
        ),
    ]
