# Generated by Django 6.0 on 2026-07-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment_resource_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
