# Generated by Django 6.0 on 2026-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_assignment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment_format',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment_original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
