# Generated by Django 6.0 on 2026-07-21 09:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('students', '0005_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display name of the fee (e.g. S5 Tuition Fee)', max_length=255)),
                ('fee_type', models.CharField(help_text='Custom fee type (e.g. Tuition, Exam, Bus, Hostel)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Information about this fee and who should pay it.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('semester', models.PositiveSmallIntegerField()),
                ('due_date', models.DateField()),
                ('late_fee_enabled', models.BooleanField(default=False)),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('eligibility', models.CharField(blank=True, help_text='Example: All Students, Grant Students, Management Quota, Self Financing Students.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=120, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('late_fee_applied', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fees.fee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['department'], name='fees_fee_departm_b01690_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['semester'], name='fees_fee_semeste_5ec0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['due_date'], name='fees_fee_due_dat_0706dc_idx'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['is_active'], name='fees_fee_is_acti_241996_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student'], name='fees_paymen_student_f6fede_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='fees_paymen_status_42ba84_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='fees_paymen_razorpa_5afcb5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='fees_paymen_created_a28d47_idx'),
        ),
    ]
