# Generated by Django 6.0 on 2026-07-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
        ('students', '0005_student_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='lostfoundpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lost & Found Post', 'verbose_name_plural': 'Lost & Found Posts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_comments', to='students.student'),
        ),
    ]
