# Generated by Django 6.0 on 2026-07-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_alter_comment_options_alter_lostfoundpost_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
